    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['menus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <section id="page-account-settings">
                    <div class="row">
                        <!-- left menu section -->
                        <div class="col-md-3 mb-2 mb-md-0">
                            <ul class="nav nav-pills flex-column nav-left">
                                <li class="nav-item">
                                    <a class="nav-link active" id="account-pill-general" data-toggle="pill" href="#account-vertical-general" aria-expanded="true">
                                        <i data-feather="user" class="font-medium-3 mr-1"></i>
                                        <span class="font-weight-bold">General</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="account-pill-password" data-toggle="pill" href="#account-vertical-password" aria-expanded="false">
                                        <i data-feather="lock" class="font-medium-3 mr-1"></i>
                                        <span class="font-weight-bold">Cambiar Contraseña</span>
                                    </a>
                                </li>
                                <!-- notification -->
                                <!-- <li class="nav-item">
                                    <a class="nav-link" id="account-pill-notifications" data-toggle="pill" href="#account-vertical-notifications" aria-expanded="false">
                                        <i data-feather="bell" class="font-medium-3 mr-1"></i>
                                        <span class="font-weight-bold">Notificaciones</span>
                                    </a>
                                </li> -->
                            </ul>
                        </div>
                        <!--/ left menu section -->

                        <!-- right content section -->
                        <div class="col-md-9">
                            <div class="card">
                                <div class="card-body">
                                    <div class="tab-content">
                                        <!-- general tab -->
                                        <div role="tabpanel" class="tab-pane active" id="account-vertical-general" aria-labelledby="account-pill-general" aria-expanded="true">

                                            <div class="media">
                                                <a class="mr-25">
                                                    <img src="<?php echo BASE_URL . $_SESSION['foto'] ?>" id="account-upload-img" class="rounded mr-50" alt="profile image" height="150" width="150" />
                                                </a>
                                                <!-- <div class="media-body mt-75 ml-1">
                                                    <label for="account-upload" class="btn btn-sm btn-success mb-75 mr-75">Subir foto</label>
                                                    <input type="file" id="account-upload" name="archivo" hidden accept="image/*" />
                                                    <button id="btnsubir" class="btn btn-sm btn-secondary mb-75">Reiniciar</button>
                                                    <p>Permitido JPG, JPEG or PNG. Tamaño máximo de 800kB</p>
                                                </div> -->
                                                <div class="row">

                                                    <div class="col-sm-12">
                                                        <div class="form-group">
                                                            <p></p>
                                                            <p>Cargar Imagen (formato jpg o png peso max. 1MB)</p>
                                                            <div class="input-group">
                                                                <div class="custom-file">
                                                                    <input type="file" name="archivo" class="custom-file-input" id="archivo">
                                                                    <label class="custom-file-label" for="exampleInputFile">Cargar archivo...</label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-sm-12">
                                                        <div class="form-group">
                                                            <button type="button" id="btnsubir" name="btnsubir" class="btn btn-success btn-block"><b>Subir imagen</b></button>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-12 col-sm-6">
                                                    <div class="form-group">
                                                        <label for="account-username">Nombres</label>
                                                        <input type="text" class="form-control" id="nombres" placeholder="nombre" autocomplete="off" value="<?php if (count($this->login) > 0) {
                                                                                                                                                                echo $this->login[0]['v_nombres'];
                                                                                                                                                            } else {
                                                                                                                                                                echo "";
                                                                                                                                                            }; ?>" />
                                                    </div>
                                                </div>
                                                <div class="col-12 col-sm-6">
                                                    <div class="form-group">
                                                        <label for="account-name">Apellidos</label>
                                                        <input type="text" class="form-control" id="apellidos" placeholder="apellidos" autocomplete="off" value="<?php if (count($this->login) > 0) {
                                                                                                                                                                        echo $this->login[0]['v_apellidos'];
                                                                                                                                                                    } else {
                                                                                                                                                                        echo "";
                                                                                                                                                                    }; ?>" />
                                                    </div>
                                                </div>
                                                <div class="col-12 col-sm-6">
                                                    <div class="form-group">
                                                        <label for="account-e-mail">Correo</label>
                                                        <input type="email" class="form-control" id="correo" placeholder="micorre@example.com" autocomplete="off" value="<?php if (count($this->login) > 0) {
                                                                                                                                                                                echo $this->login[0]['v_correo'];
                                                                                                                                                                            } else {
                                                                                                                                                                                echo "";
                                                                                                                                                                            }; ?>" />
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <button id="btnregistros" type="submit" class="btn btn-warning mt-2 mr-1 ">Guardar cambios</button>
                                                </div>
                                            </div>
                                        </div>
                                        <!--/ general tab -->

                                        <!-- change password -->
                                        <div class="tab-pane fade" id="account-vertical-password" role="tabpanel" aria-labelledby="account-pill-password" aria-expanded="false">
                                            <div class="row">
                                                <div class="col-12 col-sm-6">
                                                    <div class="form-group">
                                                        <label for="account-new-password">Nueva contraseña</label>
                                                        <div class="input-group form-password-toggle input-group-merge">
                                                            <input type="password" id="passwd" class="form-control" placeholder="Nueva contraseña" />
                                                            <div class="input-group-append">
                                                                <div class="input-group-text cursor-pointer">
                                                                    <i data-feather="eye"></i>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-12 col-sm-6">
                                                    <div class="form-group">
                                                        <label for="account-retype-new-password">Repite nueva contraseña</label>
                                                        <div class="input-group form-password-toggle input-group-merge">
                                                            <input type="password" id="passwd2" class="form-control" placeholder="Repita nueva contraseña" />
                                                            <div class="input-group-append">
                                                                <div class="input-group-text cursor-pointer"><i data-feather="eye"></i></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <button id="btnpassword" type="button" class="btn btn-warning mr-1 mt-1">Guardar cambios</button>
                                                </div>
                                            </div>
                                        </div>
                                        <!--/ change password -->
                                    </div>
                                    <!--/ subir curriculum -->

                                    <!-- notifications -->
                                    <!-- <div class="tab-pane fade" id="account-vertical-notifications" role="tabpanel" aria-labelledby="account-pill-notifications" aria-expanded="false">
                                            <div class="row">
                                                <h6 class="section-label mx-1 mb-2">Activity</h6>
                                                <div class="col-12 mb-2">
                                                    <div class="custom-control custom-switch">
                                                        <input type="checkbox" class="custom-control-input" checked id="accountSwitch1" />
                                                        <label class="custom-control-label" for="accountSwitch1">
                                                            Email me when someone comments onmy article
                                                        </label>
                                                    </div>
                                                </div>
                                                <div class="col-12 mb-2">
                                                    <div class="custom-control custom-switch">
                                                        <input type="checkbox" class="custom-control-input" checked id="accountSwitch2" />
                                                        <label class="custom-control-label" for="accountSwitch2">
                                                            Email me when someone answers on my form
                                                        </label>
                                                    </div>
                                                </div>
                                                <div class="col-12 mb-2">
                                                    <div class="custom-control custom-switch">
                                                        <input type="checkbox" class="custom-control-input" id="accountSwitch3" />
                                                        <label class="custom-control-label" for="accountSwitch3">Email me hen someone follows me</label>
                                                    </div>
                                                </div>
                                                <h6 class="section-label mx-1 mt-2">Application</h6>
                                                <div class="col-12 mt-1 mb-2">
                                                    <div class="custom-control custom-switch">
                                                        <input type="checkbox" class="custom-control-input" checked id="accountSwitch4" />
                                                        <label class="custom-control-label" for="accountSwitch4">News and announcements</label>
                                                    </div>
                                                </div>
                                                <div class="col-12 mb-2">
                                                    <div class="custom-control custom-switch">
                                                        <input type="checkbox" class="custom-control-input" checked id="accountSwitch6" />
                                                        <label class="custom-control-label" for="accountSwitch6">Weekly product updates</label>
                                                    </div>
                                                </div>
                                                <div class="col-12 mb-75">
                                                    <div class="custom-control custom-switch">
                                                        <input type="checkbox" class="custom-control-input" id="accountSwitch5" />
                                                        <label class="custom-control-label" for="accountSwitch5">Weekly blog digest</label>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <button type="submit" class="btn btn-primary mt-2 mr-1">Save changes</button>
                                                    <button type="reset" class="btn btn-outline-secondary mt-2">Cancel</button>
                                                </div>
                                            </div>
                                        </div> -->
                                    <!--/ notifications -->

                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/ right content section -->
                </section>
            </div>
            <!-- / account setting page -->

        </div>
    </div>
    </div>
    <!-- END: Content-->