    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">

            <div class="row">
                <section class="col-lg-6">
                    <div class="card col-12">
                        <div class="card-body">

                            <table id="example1" class="col-lg-12 table" cellspacing="0">
                                <thead class="thead-dark">
                                    <tr class="text-center">
                                        <th>PUESTOS PUBLICADOS</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (isset($this->publicacioncab)) { ?>
                                        <?php foreach ($this->publicacioncab as $pc) { ?>
                                            <tr>
                                                <td>
                                                    <div class="col-md-12 col-12">
                                                        <div class="d-flex justify-content-between flex-md-row flex-column mt-0">
                                                            <div>
                                                                <p class="card-text mb-0 font-weight-bolder"><?php echo $pc['v_empresa'] ?></p>
                                                                <p class="card-text mb-0"><?php echo $pc['v_departamento'] ?>, <?php echo $pc['v_provincia'] ?></p>
                                                                <div>
                                                                    <h3 class="card-text mb-1 text-success"><?php echo $pc['v_titulo'] ?></h3>
                                                                </div>
                                                                <p class="card-text mb-0"><i class="fas fa-clock"></i>&nbsp;&nbsp;<?php echo $pc['v_jornada'] ?></p>
                                                                <p class="card-text mb-0"><i class="fas fa-map-marker-alt"></i></i>&nbsp;&nbsp;<?php echo $pc['v_distrito'] ?>, <?php echo $pc['v_provincia'] ?>, <?php echo $pc['v_pais'] ?></p>
                                                            </div>
                                                            <div class="mt-md-0 mt-25">
                                                                <div class="invoice-date-wrapper">
                                                                    <p class="invoice-date-title font-weight-bolder">Publicado el <?php echo $pc['d_fecha'] ?></p>
                                                                </div>
                                                                <div class="d-flex justify-content-end">
                                                                    <button onclick="clickpuesto('<?php echo $pc['v_codigo'] ?>')" type="button" class="btn round btn-warning">
                                                                        <i data-feather='eye'></i><span>&nbsp;&nbsp;Revisar puesto</span>
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <br>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </section>
                <section class="col-lg-6">
                    <div class="card col-12">
                        <div class="card-body">
                            <div id="div-00">

                                <div class="card-header">
                                    <h4 class="card-title">VERDUM PERÚ S.A.C.</h4>
                                </div>

                                <div class="card-body">
                                    <div id="carousel-interval" class="carousel slide" data-ride="carousel" data-interval="5000">
                                        <ol class="carousel-indicators">
                                            <li data-target="#carousel-interval" data-slide-to="0" class="active"></li>
                                            <li data-target="#carousel-interval" data-slide-to="1"></li>
                                            <!-- <li data-target="#carousel-interval" data-slide-to="2"></li>
                                            <li data-target="#carousel-interval" data-slide-to="3"></li> -->
                                        </ol>
                                        <div class="carousel-inner" role="listbox">
                                            <div class="carousel-item active" data-interval="7000">
                                                <a href="https://www.mundoaltomayo.com" target="_blank">
                                                    <img class="img-fluid" href="" src="<?php echo BASE_URL ?>public/dist/img/slider/02.jpg" />
                                                </a>
                                            </div>
                                            <div class="carousel-item" data-interval="7000">
                                                <!-- <a href="https://www.youtube.com/embed/2JDVQ5J4Bic" target="_blank">
                                                    <img class="img-fluid" href="" src="<?php //echo BASE_URL ?>public/dist/img/slider/01.jpg" />
                                                </a> -->
                                                <div class="timeline-body">
                                                    <div class="embed-responsive embed-responsive-16by9">
                                                        <iframe width="560" height="315" src="https://www.youtube.com/embed/2JDVQ5J4Bic" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- <div class="carousel-item" data-interval="7000">
                                                <img class="img-fluid" src="<?php //echo BASE_URL ?>public/dist/img/slider/03.jpg" />
                                            </div>
                                            <div class="carousel-item" data-interval="7000">
                                                <img class="img-fluid" src="<?php //echo BASE_URL ?>public/dist/img/slider/04.jpg" />
                                            </div>
                                            <div class="carousel-item" data-interval="7000">
                                                <img class="img-fluid" src="<?php //echo BASE_URL ?>public/dist/img/slider/05.jpg" />
                                            </div> -->
                                        </div>
                                        <a class="carousel-control-prev" href="#carousel-interval" role="button" data-slide="prev">
                                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                        <a class="carousel-control-next" href="#carousel-interval" role="button" data-slide="next">
                                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
            </div>

        </div>

    </div>
    <!-- END: Content-->