    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['submenus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <section class="col-lg-6">
                    <div class="card col-12">
                        <div class="card-body">
                            <div class="row">

                                <div class="col-md-12 col-12">
                                    <table id="example1" class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th>#</th>
                                                <th>Cargo</th>
                                                <th># días proceso</th>
                                                <th>#</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->cargos)) { ?>
                                                <?php foreach ($this->cargos as $tr) { ?>
                                                    <tr>
                                                        <td class="text-center"><?php echo $tr['i_id'] ?></td>
                                                        <td class="text-left"><?php echo $tr['v_nombre'] ?></td>
                                                        <td class="text-center"><?php echo $tr['i_dias_proceso'] ?></td>
                                                        <td class='text-center'>
                                                            <a id="<?php echo $tr['i_id'] ?>" 
                                                            nombre="<?php echo $tr['v_nombre'] ?>"
                                                            dias="<?php echo $tr['i_dias_proceso'] ?>"
                                                            class="btn btn-warning btn-sm editar" style="color:black">
                                                                <i class="fas fa-edit"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
            </div>

        </div>
    </div>
    <!-- END: Content-->

    <!-- MODAL EDITAR DATO-->
    <div class="modal fade" id="modal-editar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">ACTUALIZAR PUESTO:&nbsp;</h5><b><span id="idtabla"></span></b>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Código:</label>
                            <input type="text" id="codigo" class="form-control" autocomplete="off" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Nombre del cargo:</label>
                            <input type="text" id="cargo" class="form-control" autocomplete="off" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Dias de proceso:</label>
                            <input type="text" id="dias" class="form-control" autocomplete="off" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <button id="btnguardar" type="button" class="btn btn-success btn-block">
                                    <i class="fas fa-save"></i>
                                    <b>Guardar</b></button>
                            </div>
                            <br>
                            <br>
                            <div class="col-sm-6">
                                <button id="btncancelar" type="button" class="btn btn-danger btn-block">
                                    <i class="fas fa-ban"></i>
                                    <b>Cancelar</b></button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>