    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b>FORMULARIO DE REGISTRO</b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">

                <div id="div00">
                    <!-- Vertical Wizard -->
                    <section class="vertical-wizard">
                        <div class="bs-stepper vertical vertical-wizard-example">
                            <div class="bs-stepper-header">
                                <!-- DATOS PERSONALES -->
                                <div id="1" class="step" data-target="#datos-personales">
                                    <button id="bt1" type="button" class="step-trigger">
                                        <span class="bs-stepper-box">1</span>
                                        <span class="bs-stepper-label">
                                            <span class="bs-stepper-title"><i class="fas fa-user"></i> | DATOS PERSONALES</span>
                                        </span>
                                    </button>
                                </div>
                                <!-- HIJOS -->
                                <div id="2" class="step" data-target="#hijos">
                                    <button id="bt2" type="button" class="step-trigger">
                                        <span class="bs-stepper-box">2</span>
                                        <span class="bs-stepper-label">
                                            <span class="bs-stepper-title"><i class="fas fa-child"></i> | HIJOS</span>
                                        </span>
                                    </button>
                                </div>
                                <!-- ESSALUD | AFP -->
                                <div id="3" class="step" data-target="#essalud">
                                    <button id="bt3" type="button" class="step-trigger">
                                        <span class="bs-stepper-box">3</span>
                                        <span class="bs-stepper-label">
                                            <span class="bs-stepper-title"><i class="fas fa-hospital-user"></i> | ESSALUD | AFP</span>
                                        </span>
                                    </button>
                                </div>
                                <!-- RTPS -->
                                <div id="4" class="step" data-target="#rtps">
                                    <button id="bt4" type="button" class="step-trigger">
                                        <span class="bs-stepper-box">4</span>
                                        <span class="bs-stepper-label">
                                            <span class="bs-stepper-title"><i class="fas fa-user-tie"></i> | RTPS</span>
                                        </span>
                                    </button>
                                </div>
                            </div>
                            <div class="bs-stepper-content">
                                <!-- DATOS PERSONALES -->
                                <div id="datos-personales" class="content">
                                    <div class="content-header">
                                        <h4 class="mb-0 font-weight-bolder">DATOS PERSONALES</h4>

                                        <body style="text-align: justify;">
                                            <small class="text">Rellenar todos los campos obligatorios, marcados con <b class="font-weight-bolder text-danger">(*)</b>.</small>
                                        </body>
                                    </div>

                                    <div class="row">

                                        <div class="form-group col-md-4">
                                            <label class="form-label font-weight-bolder">Referencia del puesto:</label>
                                            <select id="puesto" class="select2 form-control form-control-lg">
                                                <?php echo $this->refpuesto ?>
                                            </select>
                                        </div>

                                    </div>

                                    <div class="row">

                                        <div class="form-group col-md-4">
                                            <label class="form-label font-weight-bolder">NOMBRES <b class="text-danger">(*)</b></label>
                                            <div class="input-group">
                                                <input id="nombres" type="text" class="form-control" style="text-transform:uppercase;" onkeypress='return sololetras(event)' autocomplete="off">
                                                <div class="input-group-append">
                                                    <div class="input-group-text"><i class="fas fa-user"></i></div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group col-md-4">
                                            <label class="form-label font-weight-bolder">APELLIDO PATERNO <b class="text-danger">(*)</b></label>
                                            <div class="input-group">
                                                <input id="paterno" type="text" class="form-control" style="text-transform:uppercase;" onkeypress='return sololetras(event)' autocomplete="off">
                                                <div class="input-group-append">
                                                    <div class="input-group-text"><i class="fas fa-user"></i></div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group col-md-4">
                                            <label class="form-label font-weight-bolder">APELLIDO MATERNO <b class="text-danger">(*)</b></label>
                                            <div class="input-group">
                                                <input id="materno" type="text" class="form-control" style="text-transform:uppercase;" onkeypress='return sololetras(event)' autocomplete="off">
                                                <div class="input-group-append">
                                                    <div class="input-group-text"><i class="fas fa-user"></i></div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="row">

                                        <div class="form-group col-md-2">
                                            <label class="form-label font-weight-bolder">Fecha de nacimiento: <b class="text-danger">(*)</b></label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                                </div>
                                                <input type="text" id="fecha" class="form-control flatpickr-basic" placeholder="YYYY-MM-DD" />
                                            </div>
                                        </div>

                                        <div class="form-group col-md-3">
                                            <label class="form-label font-weight-bolder">TIPO DOCUMENTO <b class="text-danger">(*)</b></label>
                                            <div class="input-group">
                                                <select class="form-control" id="tipodocumento">
                                                    <?php echo $this->tipodoc ?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group col-md-3">
                                            <label class="form-label font-weight-bolder">DNI / CE. <b class="text-danger">(*)</b></label>
                                            <div class="input-group">
                                                <input id="dni" type="text" class="form-control" onkeypress='return solonumero(event)' autocomplete="off">
                                                <div class="input-group-append">
                                                    <div class="input-group-text"><i class="fas fa-id-card"></i></div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group col-md-2">
                                            <label class="form-label font-weight-bolder">SEXO <b class="text-danger">(*)</b></label>
                                            <div class="input-group">
                                                <select class="form-control" id="sexo">
                                                    <option value="0" selected>-- SELECCIONE --</option>
                                                    <option value="1">MASCULINO</option>
                                                    <option value="2">FEMENINO</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group col-md-2">
                                            <label class="form-label font-weight-bolder">ESTADO CIVIL</label>
                                            <select class="form-control" id="civil" name="civil">
                                                <?php echo $this->civil ?>
                                            </select>
                                        </div>

                                    </div>

                                    <div class="row">

                                        <div class="form-group col-md-3">
                                            <label class="form-label font-weight-bolder">PAIS <b class="text-danger">(*)</b></label>
                                            <select id="pais" class="select2 form-control form-control-lg">
                                                <?php echo $this->pais ?>
                                            </select>
                                        </div>

                                        <div class="form-group col-md-3">
                                            <label class="form-label font-weight-bolder">DEPARTAMENTO <b class="text-danger">(*)</b></label>
                                            <select id="departamento" class="select2 form-control form-control-lg">
                                                <?php echo $this->departamento ?>
                                            </select>
                                        </div>

                                        <div class="form-group col-md-3">
                                            <label class="form-label font-weight-bolder">PROVINCIA <b class="text-danger">(*)</b></label>
                                            <select id="provincia" class="select2 form-control form-control-lg">
                                                <?php echo $this->provincia ?>
                                            </select>
                                        </div>

                                        <div class="form-group col-md-3">
                                            <label class="form-label font-weight-bolder">DISTRITO <b class="text-danger">(*)</b></label>
                                            <select id="distrito" class="select2 form-control form-control-lg">
                                                <?php echo $this->distrito ?>
                                            </select>
                                        </div>

                                    </div>

                                    <div class="row">

                                        <div class="form-group col-md-12">
                                            <label class="form-label font-weight-bolder">DIRECCION ACTUAL <b class="text-danger">(*)</b></label>
                                            <div class="input-group">
                                                <input id="domicilio_actual" name="domicilio_actual" type="text" class="form-control" style="text-transform:uppercase;" placeholder="DIRECCIÓN..." autocomplete="off">
                                                <div class="input-group-append" data-target="#domicilio_actual">
                                                    <div class="input-group-text"><i class="fa fa-map-marked-alt"></i></div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="row">

                                        <div class="form-group col-md-3">
                                            <label class="form-label font-weight-bolder">N° CELULAR <b class="text-danger">(*)</b></label>
                                            <div class="input-group">
                                                <input id="celular" name="celular" type="text" class="form-control" onkeypress='return solonumero(event)' placeholder="999888777" autocomplete="off">
                                                <div class="input-group-append" data-target="#correo">
                                                    <div class="input-group-text"><i class="fa fa-mobile-alt"></i></div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group col-md-4">
                                            <label class="form-label font-weight-bolder">CORREO PERSONAL <b class="text-danger">(*)</b></label>
                                            <div class="input-group">
                                                <input id="correo" name="correo" type="email" class="form-control" aria-describedby="emailHelp" placeholder="correo@ejemplo.com" autocomplete="off">
                                                <div class="input-group-append" data-target="#correo">
                                                    <div class="input-group-text"><i class="fa fa-at"></i></div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="d-flex justify-content-between">
                                        <button class="btn btn-outline-secondary btn-prev" disabled>
                                            <i data-feather="arrow-left" class="align-middle mr-sm-25 mr-0"></i>
                                            <span class="align-middle d-sm-inline-block d-none">Anterior</span>
                                        </button>
                                        <button class="btn btn-success btn-next">
                                            <span class="align-middle d-sm-inline-block d-none">Siguiente</span>
                                            <i data-feather="arrow-right" class="align-middle ml-sm-25 ml-0"></i>
                                        </button>
                                    </div>
                                </div>
                                <!-- HIJOS -->
                                <div id="hijos" class="content">
                                    <div class="content-header">
                                        <h4 class="mb-0 font-weight-bolder">HIJOS</h4>

                                        <body style="text-align: justify;">
                                            <small class="text">Ingresar nombre y fecha de nacimiento de sus hijos, estos datos son importantes para la asignacion familiar mensual.
                                                <code class="font-weight-bolder text-danger">No incluir hijos mayores de 18 años.</code></small>
                                        </body>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12 col-12">
                                            <div class="form-group">
                                                <button id="btnagregar" type="button" class="btn btn-warning">
                                                    <i data-feather='plus'></i><span>&nbsp;&nbsp;Agregar</span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12 col-12">
                                            <table id="example" class="table table-bordered">
                                                <thead class="thead-dark">
                                                    <tr class="text-center">
                                                        <th>#</th>
                                                        <th>ACCIONES (¿Qué hace?, ¿Cómo lo hace?)</th>
                                                        <th>RESULTADO FINAL ESPERADO (¿Para qué lo hace?)</th>
                                                        <th># Eliminar</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="tablita-aci" class="text-center">
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>

                                    <br>
                                    <br>
                                    <div class="d-flex justify-content-between">
                                        <button class="btn btn-success btn-prev">
                                            <i data-feather="arrow-left" class="align-middle mr-sm-25 mr-0"></i>
                                            <span class="align-middle d-sm-inline-block d-none">Anterior</span>
                                        </button>
                                        <button class="btn btn-success btn-next">
                                            <span class="align-middle d-sm-inline-block d-none">Siguiente</span>
                                            <i data-feather="arrow-right" class="align-middle ml-sm-25 ml-0"></i>
                                        </button>
                                    </div>
                                </div>
                                <!-- ESSALUD | AFP -->
                                <div id="essalud" class="content">
                                    <div class="content-header">
                                        <h4 class="mb-0 font-weight-bolder">ESSALUD | AFP</h4>

                                        <body style="text-align: justify;">
                                            <small class="text">Favor de registrar los datos para el AFP y ESSALUD.</small>
                                        </body>
                                    </div>

                                    <div class="row">

                                        <div class="col-sm-2">
                                            <div class="form-group">
                                                <label class="form-label font-weight-bolder">TIENE SEGURO</label>
                                                <div class="input-group">
                                                    <select id="tieneseguro" class="form-control">
                                                        <option value="0" selected>NO</option>
                                                        <option value="1">SI</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label class="form-label font-weight-bolder">CODIGO ESSALUD <b class="font-weight-bolder text-danger">(Si no lo sabe dejelo vacío).</b></label>
                                                <div class="input-group">
                                                    <input id="codessalud" type="text" class="form-control" style="text-transform:uppercase;" autocomplete="off">
                                                    <!--9211011MANAJ009-->
                                                    <div class="input-group-append">
                                                        <div class="input-group-text"><i class="fas fa-hospital"></i></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="row">

                                        <div class="col-sm-2">
                                            <div class="form-group">
                                                <label class="form-label font-weight-bolder">DOMICILIADO</label>
                                                <div class="input-group">
                                                    <select id="domiciliado" class="form-control">
                                                        <option value="1" selected>SI</option>
                                                        <option value="2">NO</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">

                                        <div class="col-sm-3">
                                            <div class="form-group">
                                                <label class="form-label font-weight-bolder">AFP</label>
                                                <div class="input-group">
                                                    <select id="afp" class="form-control">
                                                        <?php echo $this->afp ?>
                                                    </select>
                                                </div>

                                            </div>
                                        </div>

                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label class="form-label font-weight-bolder">COMISION AFP <b class="font-weight-bolder text-danger">(Si no lo sabe dejelo en SELECCIONE).</b></label>
                                                <div class="input-group">
                                                    <select id="comfluapf" disabled class="form-control">
                                                        <option value="0" selected>-- SELECCIONE --</option>
                                                        <option value="1">FLUJO</option>
                                                        <option value="2">SALDO</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label class="form-label font-weight-bolder">CODIGO AFP <b class="font-weight-bolder text-danger">(Si no lo sabe dejelo vacío).</b></label>
                                                <div class="input-group">
                                                    <input id="codafp" type="text" class="form-control" style="text-transform:uppercase;" autocomplete="off">
                                                    <!--639071JMNAA9-->
                                                    <div class="input-group-append">
                                                        <div class="input-group-text"><i class="fas fa-user-shield"></i></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <br>
                                    <div class="d-flex justify-content-between">
                                        <button class="btn btn-success btn-prev">
                                            <i data-feather="arrow-left" class="align-middle mr-sm-25 mr-0"></i>
                                            <span class="align-middle d-sm-inline-block d-none">Anterior</span>
                                        </button>
                                        <button class="btn btn-success btn-next">
                                            <span class="align-middle d-sm-inline-block d-none">Siguiente</span>
                                            <i data-feather="arrow-right" class="align-middle ml-sm-25 ml-0"></i>
                                        </button>
                                    </div>
                                </div>
                                <!-- RTPS -->
                                <div id="rtps" class="content">
                                    <div class="content-header">
                                        <h4 class="mb-0 font-weight-bolder">REGISTRO DE TRABAJADORES Y PRESTADORES DE SERVICIOS</h4>

                                        <body style="text-align: justify;">
                                            <small class="text">Recoleccion de datos del trabajor.</small>
                                        </body>
                                    </div>

                                    <div class="row">

                                        <div class="col-sm-2">
                                            <div class="form-group">
                                                <label class="form-label font-weight-bolder">REGIMEN</label>
                                                <div class="input-group">
                                                    <select id="regimen" class="form-control">
                                                        <option value="0" selected>PRIVADO</option>
                                                        <option value="1">PÚBLICO</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="row">

                                        <div class="form-group col-md-6">
                                            <label class="form-label font-weight-bolder">NIVEL DE EDUCACION <b class="text-danger">(*)</b></label>
                                            <select id="niveleducacion" class="select2 form-control form-control-lg">
                                                <?php echo $this->nivelD ?>
                                            </select>
                                        </div>

                                    </div>

                                    <div class="row">

                                        <div class="form-group col-sm-2">
                                            <label class="form-label font-weight-bolder">DISCAPACIDAD</label>
                                            <select id="discapacidad" class="form-control">
                                                <option value="0" selected>NO</option>
                                                <option value="1">SI</option>
                                            </select>
                                        </div>

                                    </div>
                                    <br>
                                    <div class="d-flex justify-content-between">
                                        <button class="btn btn-success btn-prev">
                                            <i data-feather="arrow-left" class="align-middle mr-sm-25 mr-0"></i>
                                            <span class="align-middle d-sm-inline-block d-none">Previous</span>
                                        </button>
                                        <button id="btngrabar" type="submit" class="btn btn-primary">
                                            <i data-feather='save'></i><span>&nbsp;&nbsp;Guardar</span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <!-- /Vertical Wizard -->
                </div>


            </div>

        </div>
    </div>
    <!-- END: Content-->

    <!-- MODAL AGREGAR HIJOS -->
    <div class="modal fade" id="modal-agregar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">AGREGAR HIJOS</h5>
                    <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button> -->
                </div>
                <div class="modal-body">

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Acciones (¿Qué hace?, ¿Cómo se hace?):</label>
                            <textarea class="form-control" id="acciones" tabindex="1" autofocus rows="3" placeholder="escribir acciones..." autocomplete="off"></textarea>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Resultado final esperado:</label>
                            <textarea class="form-control" id="resultado" tabindex="2" rows="3" placeholder="escribir acciones..." autocomplete="off"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <button id="btnguardar" tabindex="3" type="button" class="btn btn-success btn-block"><b>Aceptar</b></button>
                            </div>
                            <br>
                            <br>
                            <div class="col-sm-6">
                                <button id="btncancelar" tabindex="4" type="button" class="btn btn-danger btn-block"><b>Cancelar</b></button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>