<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui">
    <meta name="author" content="Verdum Perú S.A.C.">
    <title>Verdum Perú (Inicio de sesión)</title>
    <!-- <link rel="shortcut icon" type="image/x-icon" href="<?php //echo BASE_URL ?>public/dist/img/favicon.ico"> -->
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo BASE_URL ?>public/dist/img/favicon.png">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <?php if (isset($_layoutParams['cssSp']) && count($_layoutParams['cssSp'])) : ?>
        <?php foreach ($_layoutParams['cssSp'] as $layoutcssSp) : ?>
            <link rel="stylesheet" href="<?php echo  $layoutcssSp ?>">
        <?php endforeach; ?>
    <?php endif; ?>
    <!-- END: Page CSS-->

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->
<!-- <body background="<?php //echo BASE_URL ?>public/dist/img/fondonav.jpg"> -->
<body class="horizontal-layout horizontal-menu blank-page navbar-floating footer-static  " data-open="hover" data-menu="horizontal-menu" data-col="blank-page">
    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <div class="auth-wrapper auth-v1 px-2">
                    <div class="auth-inner py-2">
                        <!-- Login v1 -->
                        <div class="card mb-0">
                            <div class="card-body">
                                <a class="brand-logo">
                                    <h2 class="brand-text text-success ml-1">Reclutamiento y Selección</h2>
                                </a>

                                <h4 class="card-title mb-1">Bienvenido, favor de iniciar sesión...</h4>
                                <!-- <p class="card-text mb-2">Por favor inicie sesión, sino crear una nueva cuenta.</p> -->

                                <form role="form">
                                    <div class="form-group">
                                        <label for="correo" class="form-label font-weight-bolder">Correo</label>
                                        <input id="correo" type="text" class="form-control" placeholder="micorreo@example.com" tabindex="1" autofocus autocomplete="off" />
                                    </div>

                                    <div class="form-group">
                                        <div class="d-flex justify-content-between font-weight-bolder">
                                            <label for="login-password">Contraseña</label>
                                        </div>
                                        <div class="input-group input-group-merge form-password-toggle">
                                            <input id="clave" onkeypress="pulsar(event)" type="password" class="form-control form-control-merge" name="login-password" tabindex="2" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;" />
                                            <div class="input-group-append">
                                                <span class="input-group-text cursor-pointer"><i data-feather="eye"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button id="btnlogin" type="button" class="btn btn-success btn-block" tabindex="3">Iniciar sesión</button>
                                    </div>
                                </form>

                                <p class="text-center mt-2">
                                    <span>Eres usuario nuevo?</span>
                                    <!-- <a href="page-auth-register-v1.html"> -->
                                    <a href="<?php echo BASE_URL ?>index/registro"><span>Crear una cuenta</span></a>
                                    <br>
                                    <span>Olvidastes tu clave?</span>
                                    <!-- <a href="page-auth-register-v1.html"> -->
                                    <a href="<?php echo BASE_URL ?>index/recuperarclave"><span>Recuperar mi contraseña</span></a>
                                    <br>
                                    <span>No has validado tu correo?</span>
                                    <!-- <a href="page-auth-register-v1.html"> -->
                                    <a href="<?php echo BASE_URL ?>index/validarcorreo"><span>Validar mi correo</span></a>
                                </p>

                            </div>
                        </div>
                        <!-- /Login v1 -->
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- END: Content-->

    <!-- BEGIN: Llamada a JS-->
    <?php if (isset($_layoutParams['jsSp']) && count($_layoutParams['jsSp'])) : ?>
        <?php foreach ($_layoutParams['jsSp'] as $layoutjsSp) : ?>
            <script src="<?php echo  $layoutjsSp ?>" type="text/javascript"></script>
        <?php endforeach; ?>
    <?php endif; ?>
    <!-- END: Llamada a JS-->

    <script>
        $(window).on('load', function() {
            if (feather) {
                feather.replace({
                    width: 14,
                    height: 14
                });
            }
        })
    </script>

    <?php if (isset($_layoutParams['js']) && count($_layoutParams['js'])) : ?>
        <?php foreach ($_layoutParams['js'] as $layout) : ?>
            <script src="<?php echo  $layout ?>" type="text/javascript"></script>
        <?php endforeach; ?>
    <?php endif; ?>

</body>
<!-- END: Body-->

</html>