<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui">
    <meta name="description" content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>Verdum Perú (Nuevo registro)</title>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo BASE_URL ?>public/dist/img/favicon.png">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <?php if (isset($_layoutParams['cssSp']) && count($_layoutParams['cssSp'])) : ?>
        <?php foreach ($_layoutParams['cssSp'] as $layoutcssSp) : ?>
            <link rel="stylesheet" href="<?php echo  $layoutcssSp ?>">
        <?php endforeach; ?>
    <?php endif; ?>
    <!-- END: Page CSS-->

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="horizontal-layout horizontal-menu blank-page navbar-floating footer-static  " data-open="hover" data-menu="horizontal-menu" data-col="blank-page">
    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <div class="auth-wrapper auth-v1 px-2">
                    <div class="auth-inner py-2">
                        <!-- Register v1 -->
                        <div class="card mb-0">
                            <div class="card-body">
                                <h4 class="card-title mb-1">Recuperar mi clave</h4>

                                <form role="form">
                                    <div class="form-group">
                                        <label for="ecorreo" class="form-label font-weight-bolder">Correo</label>
                                        <input id="ecorreo" type="text" class="form-control" placeholder="micorreo@example.com" tabindex="1" autofocus autocomplete="off" />
                                    </div>

                                    <div class="form-group">
                                        <button id="enviarclave" type="button" class="btn btn-success btn-block" tabindex="2">Enviar correo</button>
                                    </div>
                                </form>

                                <p class="text-center mt-2">
                                    <span>Ya tienes una cuenta?</span>
                                    <a href="<?php echo BASE_URL ?>index/index"><span>Iniciar sesión</span></a>
                                </p>

                            </div>
                        </div>
                        <!-- /Register v1 -->
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!-- END: Content-->

    <!-- BEGIN: Llamada a JS-->
    <?php if (isset($_layoutParams['jsSp']) && count($_layoutParams['jsSp'])) : ?>
        <?php foreach ($_layoutParams['jsSp'] as $layoutjsSp) : ?>
            <script src="<?php echo  $layoutjsSp ?>" type="text/javascript"></script>
        <?php endforeach; ?>
    <?php endif; ?>
    <!-- END: Llamada a JS-->

    <script>
        $(window).on('load', function() {
            if (feather) {
                feather.replace({
                    width: 14,
                    height: 14
                });
            }
        })
    </script>

    <?php if (isset($_layoutParams['js']) && count($_layoutParams['js'])) : ?>
        <?php foreach ($_layoutParams['js'] as $layout) : ?>
            <script src="<?php echo  $layout ?>" type="text/javascript"></script>
        <?php endforeach; ?>
    <?php endif; ?>


</body>
<!-- END: Body-->

</html>