    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['submenus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="basic-horizontal-layouts">
                    <div class="row">
                        <div class="col-md-12 col-12">
                            <div class="card">
                                <!-- <div class="card-header">
                                    <h4 class="card-title">Liberar puestos requeridos</h4>
                                </div> -->
                                <div class="card-body">
                                    <div class="row">

                                        <div class="col-md-12 col-12">
                                            <table id="example1" class="table table-bordered">
                                                <thead class="thead-dark">
                                                    <tr class="text-center">
                                                        <th>Código</th>
                                                        <th>Título</th>
                                                        <th>Complemento</th>
                                                        <th>Fecha inicio</th>
                                                        <th>Fecha fin</th>
                                                        <th>Estado</th>
                                                        <th>Código puesto</th>
                                                        <th>Cargo</th>
                                                        <th># Postulantes</th>
                                                        <th>Fecha Registro</th>
                                                        <th>Usuario crea</th>
                                                        <th># Ver</th>
                                                        <th># Editar</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->publicacionB)) { ?>
                                                        <?php foreach ($this->publicacionB as $tr) { ?>
                                                            <tr>
                                                                <td class="text-center"><?php echo $tr['v_codigo'] ?></td>
                                                                <td class="text-left"><?php echo $tr['v_titulo'] ?></td>
                                                                <td class="text-left"><?php echo $tr['v_complemento'] ?></td>
                                                                <td class="text-center"><?php echo $tr['d_fecha_inicio_reclutamiento'] ?></td>
                                                                <td class="text-center"><?php echo $tr['d_fecha_fin_reclutamiento'] ?></td>
                                                                <td class="text-center"><span class="badge bg-<?php echo $tr['v_estado_color'] ?>"><?php echo $tr['v_estado'] ?></span></td>
                                                                <td class="text-center"><?php echo $tr['v_puesto'] ?></td>
                                                                <td class="text-left"><?php echo $tr['v_cargo'] ?></td>
                                                                <td class="text-center"><?php echo $tr['i_postulantes'] ?></td>
                                                                <td class="text-center"><?php echo $tr['d_fecha_creacion'] ?></td>
                                                                <td class="text-center"><?php echo $tr['v_usuario_crea'] ?></td>
                                                                <td class='text-center'>
                                                                    <a href='<?php echo BASE_URL ?>publicacionesb/postulaciones_detalle/&publicacion=<?php echo $tr['v_codigo'] ?>&puesto=<?php echo $tr['v_cargo'] ?>' class='btn btn-secondary btn-sm text-black'>
                                                                        <i class='fa fa-eye'></i>
                                                                    </a>
                                                                </td>
                                                                <td class='text-center'>
                                                                    <a style="display: <?php if ($tr['v_estado'] == "terminado") {
                                                                                    echo "none";
                                                                                } else {
                                                                                    echo "compact";
                                                                                } ?>;" href='<?php echo BASE_URL ?>publicacionesb/mantenimiento_publicacion/&publicacion=<?php echo $tr['v_codigo'] ?>&puesto=<?php echo $tr['v_titulo'] ?>' class='btn btn-warning btn-sm text-black'>
                                                                        <i class='fa fa-edit'></i>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </tbody>
                                            </table>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </div>

        </div>
    </div>
    <!-- END: Content-->