    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['submenus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <section class="col-lg-12">
                    <div class="card col-12">
                        <div class="card-header">
                            <h4 class="card-title">Puestos solicitados</h4>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 col-12">
                                    <table id="example2" class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th>Código</th>
                                                <th>Cargo</th>
                                                <th># de vacantes</th>
                                                <th>fecha solicitud</th>
                                                <th>Estado</th>
                                                <th>fini publicación</th>
                                                <th>ffin publicación</th>
                                                <th>Descripcion *.pdf</th>
                                                <th># de postulantes</th>
                                                <th>Revisión</th>
                                                <th>#</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->cargossolicitados)) { ?>
                                                <?php foreach ($this->cargossolicitados as $tr) { ?>
                                                    <tr>
                                                        <td class="text-center"><?php echo $tr['i_id'] ?></td>
                                                        <td class="text-left"><?php echo $tr['v_nombre'] ?></td>
                                                        <td class="text-center"><?php echo $tr['i_cantidad'] ?></td>
                                                        <td class="text-center"><?php echo $tr['v_fecha'] ?></td>
                                                        <td class="text-center"><span class="badge bg-<?php echo $tr['v_color_estado'] ?>"><?php echo $tr['v_estado'] ?></span></td>
                                                        <td class="text-center"><?php echo $tr['v_fini_publicacion'] ?></td>
                                                        <td class="text-center"><?php echo $tr['v_ffin_publicacion'] ?></td>
                                                        <td class='text-center'>
                                                            <a href='<?php echo BASE_URL ?>generadoa/solicitud_generado/<?php echo $tr['v_codigo'] ?>' class='btn btn-danger btn-sm text-black' target="_blank">
                                                                <i class='fa fa-file-pdf'></i>&nbsp;&nbsp;pdf
                                                            </a>
                                                        </td>
                                                        <td class="text-center"><?php echo $tr['i_num_postulante'] ?></td>
                                                        <td class='text-center'>
                                                            <a href='<?php echo BASE_URL ?>solicitud/revision_detalle/&publicacion=<?php echo $tr['v_codigo_pub'] ?>&cargo=<?php echo $tr['v_nombre_cargo'] ?>' class='btn btn-warning btn-sm text-black' style="display:<?php echo $tr['v_display_cantidad'] ?>;">
                                                                <i class='fa fa-eye'></i>&nbsp;&nbsp;revisar
                                                            </a>
                                                        </td>
                                                        <td class='text-center'>
                                                            <a id="<?php echo $tr['i_id'] ?>" nombre="<?php echo $tr['v_nombre'] ?>" class="btn btn-danger btn-sm delete" style="display:<?php echo $tr['v_display'] ?>; color:white">
                                                                <i class="fas fa-trash-alt"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="row">
                <section class="col-lg-5">
                    <div class="card col-12">
                        <div class="card-header">
                            <h4 class="card-title">PUESTOS</h4>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 col-12">
                                    <table id="example1" class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th>Código</th>
                                                <th>Cargo</th>
                                                <th>#</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->cargosactivos)) { ?>
                                                <?php foreach ($this->cargosactivos as $tr) { ?>
                                                    <tr>
                                                        <td class="text-center"><?php echo $tr['i_id'] ?></td>
                                                        <td class="text-left"><?php echo $tr['v_nombre'] ?></td>
                                                        <td class='text-center'>
                                                            <a id="<?php echo $tr['i_id'] ?>" nombre="<?php echo $tr['v_nombre'] ?>" class="btn btn-warning btn-sm editar" style="color:black">
                                                                <i class="fas fa-plus"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
            </div>

        </div>
    </div>
    <!-- END: Content-->

    <!-- MODAL AGREGAR DATO-->
    <div class="modal fade" id="modal-agregar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Solicitar puesto:&nbsp;</h5><b><span id="idtabla"></span></b>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Código:</label>
                            <input type="text" id="codigo" class="form-control" autocomplete="off" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Nombre del cargo:</label>
                            <input type="text" id="cargo" class="form-control" autocomplete="off" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder"># de vacantes:</label>
                            <input type="text" id="cantidad" class="form-control validanumericos" onkeypress="return valideKey(event);" placeholder="# de candidatos..." />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <button id="btnguardar" type="button" class="btn btn-success btn-block">
                                    <i class="fas fa-save"></i>
                                    <b>Guardar</b></button>
                            </div>
                            <br>
                            <br>
                            <div class="col-sm-6">
                                <button id="btncancelar" type="button" class="btn btn-danger btn-block">
                                    <i class="fas fa-ban"></i>
                                    <b>Cancelar</b></button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>