    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['submenus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                                
                            </h2>
                            <h2>&nbsp;&nbsp;"<b><?php echo $this->cargo ?>"</b></h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-12">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h4 class="card-title text-white">Revisión de CV</h4>
                        </div>
                        <div class="card-body">
                            <br>
                            <!-- <p class="card-text">Postulantes: <b><?php //echo $this->cargo ?></b></p> -->
                            <div class="row">
                                <div class="col-xs-12 col-sm-3 col-12">
                                    <button id="selectAll" type="button" class="btn btn-success btn-block"><i class="fas fa-check-square"></i>&nbsp;&nbsp;<b>Seleccionar / deseleccionar [todos]</b></button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-12">
                                    <table id="example1" class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th>#</th>
                                                <th>Postulante</th>
                                                <th>Fecha</th>
                                                <th>Hora</th>
                                                <th>Estado</th>
                                                <th>CV (*.pdf)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->cvenviado)) { ?>
                                                <?php foreach ($this->cvenviado as $cv) { ?>
                                                    <tr>
                                                        <td class="text-center">
                                                            <div class="form-check">
                                                                <input class="form-check-input" type="checkbox" id="cbx1" value="<?php echo $cv['i_id'] ?>">
                                                                <label class="form-check-label"></label>
                                                            </div>
                                                        </td>
                                                        <td class="text-left"><?php echo $cv['v_postulante'] ?></td>
                                                        <td class="text-center"><?php echo $cv['d_fecha'] ?></td>
                                                        <td class="text-center"><?php echo $cv['v_hora'] ?></td>
                                                        <td class="text-center"><span class="badge bg-<?php echo $cv['v_estado_color'] ?>"><?php echo $cv['v_estado'] ?></span></td>
                                                        <td class="text-center">
                                                            <a id=<?php echo $cv['i_id'] ?> class="btn btn-<?php echo $cv['v_estado_cv_color'] ?> btn-sm cv" target="_blank" style="color:white" href="<?php echo BASE_URL . $cv['v_ruta'] ?>">
                                                                <i class="fas fa-file-pdf"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-xs-12 col-sm-2 col-12">
                                    <div class="form-group">
                                        <button id="btnaprobar" type="button" class="btn btn-success btn-block"><i class="fas fa-user-check"></i>&nbsp;&nbsp;<b>Aprobar</b></button>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-2 col-12">
                                    <div class="form-group">
                                        <button id="btndesaprobar" type="button" class="btn btn-danger btn-block"><i class="fas fa-user-times"></i>&nbsp;&nbsp;<b>Desaprobar</b></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-6 col-12">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h4 class="card-title text-white">Aprobados para Entrevista</h4>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-12">
                                    <table id="example2" class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th>Postulante</th>
                                                <th>Fecha</th>
                                                <th>Hora</th>
                                                <th>Estado</th>
                                                <th>CV (*.pdf)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->entrevistaapro)) { ?>
                                                <?php foreach ($this->entrevistaapro as $en) { ?>
                                                    <tr>
                                                        <td class="text-left"><?php echo $en['v_postulante'] ?></td>
                                                        <td class="text-center"><?php echo $en['d_fecha'] ?></td>
                                                        <td class="text-center"><?php echo $en['v_hora'] ?></td>
                                                        <td class="text-center"><span class="badge bg-<?php echo $en['v_estado_color'] ?>"><?php echo $en['v_estado'] ?></span></td>
                                                        <td class="text-center">
                                                            <a id=<?php echo $en['i_id'] ?> class="btn btn-danger btn-sm en" target="_blank" style="color:white" href="<?php echo BASE_URL . $en['v_ruta'] ?>">
                                                                <i class="fas fa-file-pdf"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-12">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h4 class="card-title text-white">Desaprobado para Entrevista</h4>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-12">
                                    <table id="example3" class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th>Postulante</th>
                                                <th>Fecha</th>
                                                <th>Hora</th>
                                                <th>Estado</th>
                                                <th>CV (*.pdf)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->entrevistadesapro)) { ?>
                                                <?php foreach ($this->entrevistadesapro as $end) { ?>
                                                    <tr>
                                                        <td class="text-left"><?php echo $end['v_postulante'] ?></td>
                                                        <td class="text-center"><?php echo $end['d_fecha'] ?></td>
                                                        <td class="text-center"><?php echo $end['v_hora'] ?></td>
                                                        <td class="text-center"><span class="badge bg-<?php echo $end['v_estado_color'] ?>"><?php echo $end['v_estado'] ?></span></td>
                                                        <td class="text-center">
                                                            <a id=<?php echo $end['i_id'] ?> class="btn btn-danger btn-sm en" target="_blank" style="color:white" href="<?php echo BASE_URL . $end['v_ruta'] ?>">
                                                                <i class="fas fa-file-pdf"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    </div>
    </div>
    <!-- END: Content-->

    <!-- MODAL ELIMINAR DATO-->
    <div class="modal fade" id="modal-ecorreo" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">ENVIAR CORREO:&nbsp;</h5><b><span id="idtabla"></span></b>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id='div-00' class="modal-body">

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Nombre:</label>
                            <input type="text" id="postnombre" class="form-control" autocomplete="off" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">correo:</label>
                            <input type="text" id="postcorreo" class="form-control" autocomplete="off" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Asunto:</label>
                            <input type="text" id="postasunto" class="form-control" autocomplete="off" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">mensaje:</label>
                            <textarea class="form-control" maxlength="1200" id="mensaje" onpaste="caracteres_mision();" onkeyup="caracteres_mision();" rows="5" placeholder="escribir breve mensaje..." autocomplete="off"></textarea>
                            <br>
                            <div class="text" id="res">
                                <small><b>0 caractere/s, te quedan 1200</b></small>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <button id="btnaceptar" type="button" class="btn btn-success btn-block">
                                    <i class="fas fa-paper-plane"></i>
                                    <b>Enviar</b></button>
                            </div>
                            <br>
                            <br>
                            <div class="col-sm-6">
                                <button id="btncancelar" type="button" class="btn btn-danger btn-block">
                                    <i class="fas fa-ban"></i>
                                    <b>Cancelar</b></button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>