    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['submenus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="basic-horizontal-layouts">
                    <div class="row">
                        <div class="col-md-12 col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-12 col-12">
                                            <table id="example1" class="table table-bordered">
                                                <thead class="thead-dark">
                                                    <tr class="text-center">
                                                        <th>#</th>
                                                        <th>Código</th>
                                                        <th>Puesto</th>
                                                        <th>Estado</th>
                                                        <th>Usuario Genera</th>
                                                        <th>Fecha Registro</th>
                                                        <th>Ultima Actualización</th>
                                                        <th># *pdf</th>
                                                        <th>#</th>
                                                        <th>#</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->generado)) { ?>
                                                        <?php foreach ($this->generado as $tr) { ?>
                                                            <tr>
                                                                <td class="text-center"><?php echo $tr['i_id'] ?></td>
                                                                <td class="text-center"><?php echo $tr['v_codigo'] ?></td>
                                                                <td class="text-left"><?php echo $tr['v_nombre_cargo'] ?></td>
                                                                <td class="text-center"><span class="badge bg-<?php echo $tr['v_color_estado'] ?>"><?php echo $tr['v_estado'] ?></span></td>
                                                                <td class="text-center"><?php echo $tr['v_usuario_genera'] ?></td>
                                                                <td class="text-center"><?php echo $tr['d_fecha_registro'] ?></td>
                                                                <td class="text-center">
                                                                    <a style="display: <?php echo $tr['v_actualizacion'] ?>;">
                                                                        <?php echo $tr['d_fecha_actualizacion'] ?>
                                                                    </a>
                                                                </td>
                                                                <td class='text-center'>
                                                                    <a href='<?php echo BASE_URL ?>generadoa/solicitud_generado/<?php echo $tr['v_codigo'] ?>' class='btn btn-danger btn-sm text-black' target="_blank">
                                                                        <i class='fa fa-file-pdf'></i>
                                                                    </a>
                                                                </td>
                                                                <td class='text-center'>
                                                                    <a href='<?php echo BASE_URL ?>generadoa/detalle_generado/&codigo=<?php echo $tr['v_codigo'] ?>&cargo=<?php echo $tr['v_nombre_cargo'] ?>' class='btn btn-warning btn-sm text-black'>
                                                                        <i class='fa fa-edit'></i>
                                                                    </a>
                                                                </td>
                                                                <td class='text-center'>
                                                                    <a id="<?php echo $tr['v_codigo'] ?>" puestoa="<?php echo $tr['v_nombre_cargo'] ?>" class="btn btn-danger btn-sm delete text-white">
                                                                        <i class="fas fa-trash-alt"></i>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </tbody>
                                            </table>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </div>

        </div>
    </div>
    <!-- END: Content-->